(()=>{"use strict";
const valid=v=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function color(v){const ranks=window.ADRIAN_VISUAL_SYSTEM?.ranks||[];return ranks[Math.max(0,Math.min(14,Math.ceil(v/100*15)-1))]?.color||"#57965A";}
function inject(){if(document.getElementById("hub-chart-style"))return;const s=document.createElement("style");s.id="hub-chart-style";s.textContent=`
.hub-chart{margin:14px 0;padding:14px;border:1px solid #34483d;border-radius:14px;background:#101815;color:#eef5f0;font:400 14px/1.45 system-ui;min-width:0}.hub-chart h3{margin:0 0 8px;font-size:16px}.hub-chart svg{display:block;width:100%;height:auto;max-height:none!important;aspect-ratio:600/280}.hub-chart-meta{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:8px;color:#bdd0c3}.hub-chart p{margin:8px 0 0;color:#bdd0c3}.hub-chart-empty{padding:18px 0;color:#bdd0c3}.adp-card span,.adp-kicker,.adp-score span{font-size:14px!important;letter-spacing:0!important}.adp-note{font-size:14px!important}.adp-actions button{font-size:14px!important;min-height:44px!important}.adp-skill{font-size:14px!important}

.hub-chart{background:linear-gradient(145deg,#1e382a,#101b16);border-color:#6a806f}.hub-chart svg{aspect-ratio:600/320}.hc-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px}.hc-head h3{margin:0}.hub-chart button,.hc-dialog button,.hc-controls select,.hc-controls input{box-sizing:border-box;min-height:44px;border:1px solid #72977f;border-radius:10px;padding:8px 12px;color:#f3faf5;background:#244632;font:600 14px/1.3 system-ui}.hc-inspector{margin:10px 0 0;padding:10px 12px;background:#111e17;border:1px solid #52745e;border-radius:10px;color:#e4f1e8;font-size:14px;min-height:44px}.hc-dialog{box-sizing:border-box;width:min(1240px,calc(100vw - 16px));max-width:none;max-height:calc(100dvh - 16px);padding:20px;border:1px solid #8aac94;border-radius:18px;background:#152b20;color:#f1f8f3;overflow:auto;font:400 16px/1.45 system-ui;z-index:10000}.hc-dialog::backdrop{background:rgba(3,9,6,.9)}.hc-dialog-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.hc-dialog h2{margin:0;font-size:24px}.hc-controls{display:flex;flex-wrap:wrap;gap:12px;align-items:end;margin:16px 0}.hc-controls label{display:grid;gap:4px;font-size:14px}.hc-controls .hc-check{display:flex;align-items:center;gap:6px;min-height:44px}.hc-check input{min-height:24px;width:22px;accent-color:#e7bf57}.hc-dialog .hub-chart svg{aspect-ratio:1100/560}.hc-dialog .hub-chart{margin:0}.hub-chart button:focus-visible,.hc-dialog button:focus-visible{outline:3px solid #e7bf57;outline-offset:3px}@media(max-width:620px){.hub-chart svg{aspect-ratio:360/300}.hc-dialog{padding:12px}.hc-dialog h2{font-size:20px}.hc-dialog .hub-chart{padding:10px}.hc-dialog .hub-chart svg{aspect-ratio:360/380}.hc-controls input[type=date]{max-width:160px}}
`;document.head.append(s);}

const chartConfigs=new Map();let chartSequence=0;
const stamp=v=>valid(v)&&Number(v)>0?new Date(Number(v)).toLocaleString("es-ES",{timeZone:"Europe/Madrid",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"Sin fecha registrada";
const day=v=>valid(v)&&Number(v)>0?new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Madrid"}).format(new Date(Number(v))):"";
function prepareRows(rows,opts){let rs=rows.map(r=>({...r,at:typeof r.at==="string"?Date.parse(r.at):r.at}));if(opts.from)rs=rs.filter(r=>day(r.at)>=opts.from);if(opts.to)rs=rs.filter(r=>day(r.at)<=opts.to);if(opts.daily){const groups=new Map();for(const r of rs){const key=day(r.at);if(!key||!valid(r.value))continue;let g=groups.get(key);if(!g){g={at:r.at,value:0,target:0,n:0,nt:0};groups.set(key,g);}const weight=valid(r.weight)&&Number(r.weight)>0?Number(r.weight):1;g.value+=Number(r.value)*weight;g.n+=weight;if(valid(r.target)){g.target+=Number(r.target)*weight;g.nt+=weight;}}rs=[...groups.values()].sort((a,b)=>a.at-b.at).map((g,i)=>({...g,index:i+1,value:g.value/g.n,target:g.nt?g.target/g.nt:null}));}return rs;}
function chartInspect(host,index){const cfg=chartConfigs.get(host.dataset.hcId),r=cfg?.rendered[index];if(!r||!valid(r.value))return;const unit=cfg.opts.unit??"%",dlg=host.closest(".hc-dialog");let text=(r.label||"Sesión "+r.index)+" · "+stamp(r.at)+" · "+Number(r.value).toFixed(1)+unit+(valid(r.target)?" · Objetivo "+Number(r.target).toFixed(1)+unit:"");if(dlg?.querySelector("[data-hc-compare]")?.checked){if(!dlg._compare||dlg._compare.length===2)dlg._compare=[];dlg._compare.push(r);if(dlg._compare.length===2){const [a,b]=dlg._compare,d=Number(b.value)-Number(a.value);text=stamp(a.at)+": "+Number(a.value).toFixed(1)+unit+" · "+stamp(b.at)+": "+Number(b.value).toFixed(1)+unit+" · Diferencia "+(d>=0?"+":"")+d.toFixed(1)+(unit==="%"?" puntos":unit);}else text+=" · Elige el segundo punto.";}const el=host.querySelector(".hc-inspector");if(el)el.textContent=text;}
function chartOpen(id,opener){const cfg=chartConfigs.get(id);if(!cfg)return;const old=document.getElementById("hc-dialog");if(old){old.close();old.remove();}const dlg=document.createElement("dialog");dlg.id="hc-dialog";dlg.className="hc-dialog";dlg.setAttribute("aria-label",cfg.opts.title||"Histórico");const dated=cfg.rows.some(r=>day(r.at)),hasTarget=cfg.rows.some(r=>valid(r.target));dlg.innerHTML='<div class="hc-dialog-head"><h2>'+esc(cfg.opts.title||"Histórico")+'</h2><button type="button" data-hc-close>Cerrar</button></div><div class="hc-controls"><label>Vista<select data-hc-view><option value="sessions">Todas las sesiones</option>'+(dated?'<option value="days">Por días</option>':"")+'</select></label>'+(dated?'<label>Desde<input type="date" data-hc-from></label><label>Hasta<input type="date" data-hc-to></label>':"")+'<button type="button" data-hc-reset>Todo el histórico</button><label class="hc-check"><input type="checkbox" data-hc-compare>Comparar dos puntos</label>'+(hasTarget?'<label class="hc-check"><input type="checkbox" data-hc-target checked>Mostrar objetivo</label>':"")+'</div><div data-hc-content></div>';document.body.append(dlg);const overflow=document.body.style.overflow;document.body.style.overflow="hidden";dlg.addEventListener("close",()=>{document.body.style.overflow=overflow;opener?.focus?.({preventScroll:true});});const refresh=()=>{dlg._compare=[];dlg.querySelector("[data-hc-content]").innerHTML=chart(cfg.rows,{...cfg.opts,expanded:true,daily:dlg.querySelector("[data-hc-view]").value==="days",from:dlg.querySelector("[data-hc-from]")?.value,to:dlg.querySelector("[data-hc-to]")?.value,showTarget:dlg.querySelector("[data-hc-target]")?.checked??true});};dlg.addEventListener("change",refresh);dlg.querySelector("[data-hc-close]").onclick=()=>dlg.close();dlg.querySelector("[data-hc-reset]").onclick=()=>{for(const el of dlg.querySelectorAll('input[type=date]'))el.value="";dlg.querySelector("[data-hc-view]").value="sessions";refresh();};dlg.addEventListener("click",e=>{if(e.target===dlg){const r=dlg.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dlg.close();}});refresh();dlg.showModal();dlg.querySelector("[data-hc-close]").focus();}
document.addEventListener("click",e=>{const button=e.target.closest?.("[data-hc-open]");if(button){chartOpen(button.dataset.hcOpen,button);return;}const host=e.target.closest?.(".hub-chart"),svg=e.target.closest?.(".hub-chart svg");if(!host||!svg)return;let index=e.target.closest?.("[data-hc-point]")?.dataset.hcPoint;if(index===undefined){const rect=svg.getBoundingClientRect(),vx=(e.clientX-rect.left)/rect.width*svg.viewBox.baseVal.width;let best=Infinity;for(const point of svg.querySelectorAll("[data-hc-point]")){const d=Math.abs(Number(point.getAttribute("cx"))-vx);if(d<best){best=d;index=point.dataset.hcPoint;}}}if(index!==undefined)chartInspect(host,Number(index));});
document.addEventListener("keydown",e=>{const point=e.target.closest?.("[data-hc-point]");if(point&&(e.key==="Enter"||e.key===" ")){e.preventDefault();chartInspect(point.closest(".hub-chart"),Number(point.dataset.hcPoint));}});

function chart(rows=[],opts={}){inject();const max=opts.max||100,unit=opts.unit??"%",title=opts.title||"Evolución",all=rows.map((r,i)=>typeof r==="number"?{value:r,index:i+1}:({...r,index:r.index??i+1})),rs=prepareRows(all,opts),good=rs.filter(r=>valid(r.value));const chartId="hc-"+(++chartSequence);chartConfigs.set(chartId,{rows:all,opts,rendered:rs});
if(!good.length)return `<section class="hub-chart" data-hc-id="${chartId}"><div class="hc-head"><h3>${esc(title)}</h3>${opts.expanded?"":`<button type="button" data-hc-open="${chartId}">Ampliar</button>`}</div><div class="hub-chart-empty">La gráfica aparecerá cuando haya respuestas registradas.</div>${opts.note?`<p>${esc(opts.note)}</p>`:""}</section>`;
const W=opts.expanded&&innerWidth>620?1100:innerWidth<=620?360:600,H=opts.expanded?(innerWidth>620?560:380):300,L=48,R=20,T=18,B=54,dated=rs.every(r=>valid(r.at)&&Number(r.at)>0),firstAt=Number(rs[0].at),lastAt=Number(rs.at(-1).at),x=i=>L+(rs.length===1?.5:dated&&lastAt>firstAt?(Number(rs[i].at)-firstAt)/(lastAt-firstAt):i/(rs.length-1))*(W-L-R),y=v=>T+(1-Math.max(0,Math.min(max,v))/max)*(H-T-B);
const ranks=window.ADRIAN_VISUAL_SYSTEM?.ranks||[],bands=ranks.map((r,i)=>`<rect x="${L}" y="${y(max*(i+1)/15)}" width="${W-L-R}" height="${(H-T-B)/15+.2}" fill="${r.band||r.color}" opacity=".82"/>`).join("");
const ticks=max===15?Array.from({length:16},(_,i)=>i):Array.from({length:5},(_,i)=>i*max/4),grid=ticks.map(v=>`<line x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}" stroke="#92aa9a" opacity=".25"/><text x="${L-8}" y="${y(v)+5}" text-anchor="end" fill="#c8d9cd" font-size="14">${Number(v.toFixed(1))}</text>`).join("");
let lines="",prev=null;rs.forEach((r,i)=>{if(!valid(r.value)){prev=null;return;}const p={x:x(i),y:y(r.value),r};if(prev)lines+=`<line x1="${prev.x}" y1="${prev.y}" x2="${p.x}" y2="${p.y}" stroke="${color(Number(r.value)/max*100)}" stroke-width="3.5" stroke-linecap="round"/>`;prev=p;});
const dots=rs.map((r,i)=>!valid(r.value)?"":`<circle data-hc-point="${i}" tabindex="0" role="button" aria-label="${esc(stamp(r.at)+": "+Number(r.value).toFixed(1)+unit)}" cx="${x(i)}" cy="${y(r.value)}" r="4.5" fill="${color(Number(r.value)/max*100)}" stroke="#eef5f0" stroke-width="1.5"><title>${esc((r.at?new Date(r.at).toLocaleDateString("es-ES")+" · ":"")+Number(r.value).toFixed(1)+unit+(r.n?" · "+r.n+" respuestas":""))}</title></circle>`).join("");
const count=Math.min(opts.expanded?(innerWidth>620?7:5):4,rs.length),indices=[...new Set(Array.from({length:count},(_,k)=>count===1?0:Math.round(k*(rs.length-1)/(count-1))))],labels=indices.map(i=>'<text x="'+x(i)+'" y="'+(H-26)+'" text-anchor="'+(i===0?'start':i===rs.length-1?'end':'middle')+'" fill="#deeee3" font-size="14">'+esc(dated?new Date(Number(rs[i].at)).toLocaleDateString('es-ES',{timeZone:'Europe/Madrid',day:'2-digit',month:'short'}):rs[i].index)+'</text>').join('');let targetMarkup="",targetPrevious=null;rs.forEach((r,i)=>{if(!valid(r.target)||opts.showTarget===false){targetPrevious=null;return;}const p={x:x(i),y:y(Number(r.target))};if(targetPrevious)targetMarkup+='<line x1="'+targetPrevious.x+'" y1="'+targetPrevious.y+'" x2="'+p.x+'" y2="'+p.y+'" stroke="#fff2b0" stroke-width="2.5" stroke-dasharray="7 5"/>';targetMarkup+='<circle cx="'+p.x+'" cy="'+p.y+'" r="3" fill="#15261c" stroke="#fff2b0" stroke-width="1.5"/>';targetPrevious=p;});const last=good.at(-1),delta=good.length>1?Number(last.value)-Number(good[0].value):null;
return `<section class="hub-chart" data-hc-id="${chartId}"><div class="hc-head"><h3>${esc(title)}</h3>${opts.expanded?"":`<button type="button" data-hc-open="${chartId}">Ampliar</button>`}</div><svg role="img" aria-label="${esc(title)}" viewBox="0 0 ${W} ${H}"><rect x="${L}" y="${T}" width="${W-L-R}" height="${H-T-B}" fill="#101815"/>${bands}${grid}${targetMarkup}${lines}${dots}${labels}<text x="${L}" y="${H-5}" fill="#deeee3" font-size="14">${dated?"Fecha":"Sesiones"}${targetMarkup?" · Discontinua: objetivo":""}</text></svg><div class="hub-chart-meta"><span>Último: ${Number(last.value).toFixed(1)}${esc(unit)}</span><span>${delta===null?"Primer registro":(delta>=0?"+":"")+delta.toFixed(1)+(unit==="%"?" puntos":unit)} · ${good.length} ${opts.daily?"días":"registros"}</span></div><p class="hc-range">${dated?esc(stamp(rs[0].at)+" — "+stamp(rs.at(-1).at)):"Sesión "+rs[0].index+" — "+rs.at(-1).index} · ${opts.from||opts.to?"Periodo seleccionado":"Histórico completo"}</p><div class="hc-inspector" aria-live="polite">Toca un punto para ver fecha y resultado.</div>${opts.note?`<p>${esc(opts.note)}</p>`:""}</section>`;}
function automaticity(answers=[],threshold=4){const rows=answers.filter(a=>a&&valid(a.sec)&&Number(a.sec)>0&&typeof a.correct==="boolean").map(a=>({...a,sec:Number(a.sec)}));const points=[];for(let end=Math.min(15,rows.length);end>0;end=Math.min(rows.length,end+15)){const sample=rows.slice(Math.max(0,end-60),end);points.push({at:sample.at(-1).at,index:end,n:sample.length,value:100*sample.filter(a=>a.correct&&a.sec<=threshold).length/sample.length,avgSec:sample.reduce((n,a)=>n+a.sec,0)/sample.length});if(end===rows.length)break;}return{rows:points,current:points.at(-1)?.value??null,avgSec:points.at(-1)?.avgSec??null,n:rows.length,threshold};}
function charts(snap){const a=automaticity(snap.automaticityAnswers||[],snap.automaticityThresholdSec||4);return chart((snap.history||[]).map(r=>({at:r.at,value:r.score15,target:r.target15,label:r.label,weight:r.total})),{max:15,unit:" /15",title:"Resultados · histórico completo"})+chart((snap.history||[]).map(r=>({at:r.at,value:r.learning})),{title:"Línea de aprendizaje · histórico completo",note:"Evolución del índice de aprendizaje de esta aplicación."})+chart(a.rows,{title:"Automatismo",note:`Aciertos en ≤ ${a.threshold} s / respuestas con tiempo registrado. Cada punto resume hasta 60 respuestas; se muestra toda la evolución disponible. El tiempo de lectura previa queda fuera. ${a.n} respuestas disponibles.`})+chart(a.rows.map(r=>({...r,value:r.avgSec})),{max:Math.max(5,...a.rows.map(r=>r.avgSec))*1.1,unit:" s",title:"Tiempo de respuesta",note:"Mismas ventanas que Automatismo. Menor tiempo junto con aciertos muestra una respuesta más fluida."});}
window.HubCharts=Object.freeze({version:"1.1.0",chart,automaticity,charts,open:(rows,opts={})=>{chart(rows,opts);chartOpen("hc-"+chartSequence,document.activeElement);}});})();
