(()=>{"use strict";
const valid=v=>v!==null&&v!==undefined&&v!==""&&Number.isFinite(Number(v));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function color(v){const ranks=window.ADRIAN_VISUAL_SYSTEM?.ranks||[];return ranks[Math.max(0,Math.min(14,Math.ceil(v/100*15)-1))]?.color||"#57965A";}
function inject(){if(document.getElementById("hub-chart-style"))return;const s=document.createElement("style");s.id="hub-chart-style";s.textContent=`
.hub-chart{margin:14px 0;padding:14px;border:1px solid #34483d;border-radius:14px;background:#101815;color:#eef5f0;font:400 14px/1.45 system-ui;min-width:0}.hub-chart h3{margin:0 0 8px;font-size:16px}.hub-chart svg{display:block;width:100%;height:auto;max-height:none!important;aspect-ratio:600/280}.hub-chart-meta{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:8px;color:#bdd0c3}.hub-chart p{margin:8px 0 0;color:#bdd0c3}.hub-chart-empty{padding:18px 0;color:#bdd0c3}.adp-card span,.adp-kicker,.adp-score span{font-size:14px!important;letter-spacing:0!important}.adp-note{font-size:14px!important}.adp-actions button{font-size:14px!important;min-height:44px!important}.adp-skill{font-size:14px!important}
`;document.head.append(s);}
function chart(rows=[],opts={}){inject();const max=opts.max||100,unit=opts.unit??"%",title=opts.title||"Evolución",all=rows.map((r,i)=>typeof r==="number"?{value:r,index:i+1}:({...r,index:r.index??i+1})),rs=all.slice(-60),good=rs.filter(r=>valid(r.value));
if(!good.length)return `<section class="hub-chart"><h3>${esc(title)}</h3><div class="hub-chart-empty">La gráfica aparecerá cuando haya respuestas registradas.</div>${opts.note?`<p>${esc(opts.note)}</p>`:""}</section>`;
const W=600,H=280,L=48,R=18,T=18,B=34,x=i=>L+(rs.length===1?.5:i/(rs.length-1))*(W-L-R),y=v=>T+(1-Math.max(0,Math.min(max,v))/max)*(H-T-B);
const ranks=window.ADRIAN_VISUAL_SYSTEM?.ranks||[],bands=ranks.map((r,i)=>`<rect x="${L}" y="${y(max*(i+1)/15)}" width="${W-L-R}" height="${(H-T-B)/15+.2}" fill="${r.color}" opacity=".16"/>`).join("");
const ticks=Array.from({length:5},(_,i)=>i*max/4),grid=ticks.map(v=>`<line x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}" stroke="#92aa9a" opacity=".25"/><text x="${L-8}" y="${y(v)+5}" text-anchor="end" fill="#c8d9cd" font-size="14">${Number(v.toFixed(1))}</text>`).join("");
let lines="",prev=null;rs.forEach((r,i)=>{if(!valid(r.value)){prev=null;return;}const p={x:x(i),y:y(r.value),r};if(prev)lines+=`<line x1="${prev.x}" y1="${prev.y}" x2="${p.x}" y2="${p.y}" stroke="#f2f7f4" stroke-width="3" stroke-linecap="round"/>`;prev=p;});
const dots=rs.map((r,i)=>!valid(r.value)?"":`<circle cx="${x(i)}" cy="${y(r.value)}" r="4.5" fill="${color(Number(r.value)/max*100)}" stroke="#eef5f0" stroke-width="1.5"><title>${esc((r.at?new Date(r.at).toLocaleDateString("es-ES")+" · ":"")+Number(r.value).toFixed(1)+unit+(r.n?" · "+r.n+" respuestas":""))}</title></circle>`).join("");
const last=good.at(-1),delta=good.length>1?Number(last.value)-Number(good[0].value):null;
return `<section class="hub-chart"><h3>${esc(title)}</h3><svg role="img" aria-label="${esc(title)}" viewBox="0 0 ${W} ${H}"><rect x="${L}" y="${T}" width="${W-L-R}" height="${H-T-B}" fill="#101815"/>${bands}${grid}${lines}${dots}<text x="${L}" y="${H-9}" fill="#c8d9cd" font-size="14">${esc(rs[0]?.index??1)}</text><text x="${W-R}" y="${H-9}" text-anchor="end" fill="#c8d9cd" font-size="14">${esc(rs.at(-1)?.index??rs.length)}</text></svg><div class="hub-chart-meta"><span>Último: ${Number(last.value).toFixed(1)}${esc(unit)}</span><span>${delta===null?"Primer registro":(delta>=0?"+":"")+delta.toFixed(1)+(unit==="%"?" puntos":unit)} · ${good.length} registros</span></div>${opts.note?`<p>${esc(opts.note)}</p>`:""}</section>`;}
function automaticity(answers=[],threshold=4){const rows=answers.filter(a=>a&&valid(a.sec)&&Number(a.sec)>0&&typeof a.correct==="boolean").map(a=>({...a,sec:Number(a.sec)}));const points=[];for(let end=Math.min(15,rows.length);end>0;end=Math.min(rows.length,end+15)){const sample=rows.slice(Math.max(0,end-60),end);points.push({at:sample.at(-1).at,index:end,n:sample.length,value:100*sample.filter(a=>a.correct&&a.sec<=threshold).length/sample.length,avgSec:sample.reduce((n,a)=>n+a.sec,0)/sample.length});if(end===rows.length)break;}return{rows:points,current:points.at(-1)?.value??null,avgSec:points.at(-1)?.avgSec??null,n:rows.length,threshold};}
function charts(snap){const a=automaticity(snap.automaticityAnswers||[],snap.automaticityThresholdSec||4);return chart((snap.history||[]).map(r=>({at:r.at,value:r.score15})),{max:15,unit:" /15",title:"Resultados"})+chart((snap.history||[]).map(r=>({at:r.at,value:r.learning})),{title:"Línea de aprendizaje",note:"Evolución del índice de aprendizaje de esta aplicación."})+chart(a.rows,{title:"Automatismo",note:`Aciertos en ≤ ${a.threshold} s / respuestas con tiempo registrado. Ventana móvil de hasta 60 respuestas; un punto cada 15. El tiempo de lectura previa queda fuera. ${a.n} respuestas disponibles.`})+chart(a.rows.map(r=>({...r,value:r.avgSec})),{max:Math.max(5,...a.rows.map(r=>r.avgSec))*1.1,unit:" s",title:"Tiempo de respuesta",note:"Mismas ventanas que Automatismo. Menor tiempo junto con aciertos muestra una respuesta más fluida."});}
window.HubCharts=Object.freeze({version:"1.0.0",chart,automaticity,charts});})();
