'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{Readable}=require('node:stream');
const root=path.join(__dirname,'..'),client=fs.readFileSync(path.join(root,'components/adrian-sync.js'),'utf8'),server=fs.readFileSync(path.join(root,'../adrian-sync-server/server.js'),'utf8');
const key='cambridgeB2ExerciseStatsV3',attempt=(id,n=1)=>({id,exerciseId:'exam-11-part-2',correct:n,total:8,completedAt:'2026-10-07T00:00:00.000Z',items:[{correct:true}]}),state=(...rows)=>JSON.stringify({attempts:rows});
function policy(source){const start=source.indexOf('function mergeProgress('),end=source.indexOf('function progressScore(',start);return vm.runInNewContext(source.slice(start,end)+';mergeProgress');}
const join=policy(client),serverJoin=policy(server),a=state(attempt('a')),b=state(attempt('b')),c=state(attempt('c'));
const ids=s=>JSON.parse(s).attempts.map(x=>x.id);
assert.deepEqual(ids(join(key,a,b)),['a','b']);
assert.equal(join(key,a,b),join(key,b,a),'commutative');
assert.equal(join(key,join(key,a,b),c),join(key,a,join(key,b,c)),'associative');
assert.equal(join(key,join(key,a,b),join(key,a,b)),join(key,a,b),'idempotent');
assert.equal(serverJoin(key,a,b),join(key,a,b),'client and server use identical policy');
assert.equal(join(key,a,state(attempt('a',2))),null,'same identifier with different result remains conflict');
assert.equal(join(key,a,'{"attempts":[{}]}'),null,'unidentified legacy attempts remain conflict');
assert.equal(join(key,'{"attempts":[],"reset":1}','{"attempts":[]}'),null,'unknown metadata never overwritten');
assert.equal(join('pizarras_state_v1',a,b),null,'aggregate schemas never guessed');
let handler,saved;
const initial={schema:1,revision:10,entries:{[key]:{value:a,deleted:false,updatedAt:100,deviceId:'A',revision:10}}};
const fakeFs={mkdirSync(){},readFileSync(){return JSON.stringify(initial);},appendFileSync(){},existsSync(){return false;},writeFileSync(p,v){saved=JSON.parse(v);},renameSync(){}};
vm.runInNewContext(server,{require(n){if(n==='http')return{createServer(fn){handler=fn;return{listen(p,h,f){f();}};}};if(n==='fs')return fakeFs;return require(n);},__dirname:'.',Buffer,URL,console:{log(){}},Date,JSON,Set,Object,Number,String});
function request(method,url,body){return new Promise((resolve,reject)=>{const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]);req.method=method;req.url=url;req.headers={host:'localhost',origin:'https://adrianxds-ads.github.io'};const res={statusCode:200,setHeader(){},end(v){resolve({status:this.statusCode,data:JSON.parse(String(v))});}};Promise.resolve(handler(req,res)).catch(reject);});}
(async()=>{
 const r=await request('POST','/sync',{deviceId:'B',changes:{[key]:{value:b,updatedAt:50,deleted:false}}});
 assert.deepEqual(r.data.acceptedKeys,[],'joined values must not acknowledge stale payload; old clients must reconcile');
 assert.equal(r.data.accepted,0);
 assert.deepEqual(r.data.mergedKeys,[key]);assert.deepEqual(ids(saved.entries[key].value),['a','b']);
 const duplicate=await request('POST','/sync',{deviceId:'B',changes:{[key]:{value:b,updatedAt:50}}});
 assert.equal(duplicate.data.accepted,0);assert.deepEqual(ids(saved.entries[key].value),['a','b'],'retry never double-counts');
 const collision=await request('POST','/sync',{deviceId:'C',changes:{[key]:{value:state(attempt('a',2)),updatedAt:200}}});
 assert.equal(collision.data.accepted,0);assert.deepEqual(ids(saved.entries[key].value),['a','b']);
 const deletion=await request('POST','/sync',{deviceId:'C',changes:{[key]:{deleted:true,updatedAt:300}}});assert.equal(deletion.data.accepted,0);
 const existing=fs.readFileSync(path.join(__dirname,'sync-integrity.cjs'),'utf8');
 const env=vm.runInNewContext(existing.slice(0,existing.indexOf('(async()=>'))+';env',{require,__dirname,console});
 const e=env({[key]:b},{entries:{[key]:{value:a,updatedAt:100}},revision:10});
 await e.context.window.AdrianSync.pull(false);
 assert.deepEqual(ids(e.localStorage.getItem(key)),['a','b']);
 assert([...e.localStorage.data.keys()].some(k=>k.startsWith(key+'_recovery_')),'local history backed up before join');
 assert(JSON.parse(e.localStorage.getItem('adrian_sync_meta_v1')).pending[key],'union queued for server');
 const restarted=env(Object.fromEntries(e.localStorage.data));
 assert(JSON.parse(restarted.localStorage.getItem('adrian_sync_meta_v1')).pending[key],'merge survives reload');
 e.context.fetch=async(url,opts)=>{const r=await request(opts?.method||'GET',url.replace(/^https:\/\/[^/]+\/hub-sync/,''),opts?.body?JSON.parse(opts.body):null);return {ok:r.status===200,json:async()=>r.data};};
 assert.equal(await e.context.window.AdrianSync.flush(),true);
 assert.deepEqual(ids(e.localStorage.getItem(key)),['a','b']);
 const f=env({[key]:c},{entries:{[key]:{value:saved.entries[key].value,updatedAt:100}},revision:10});
 f.context.fetch=e.context.fetch;f.localStorage.setItem(key,c);
 assert.equal(await f.context.window.AdrianSync.flush(),true,'server merge acknowledgement pulls joined history before claiming success');
 assert.deepEqual(ids(f.localStorage.getItem(key)),['a','b','c']);
 assert(!JSON.parse(f.localStorage.getItem('adrian_sync_meta_v1')).pending[key]);
 console.log('PASS conservative merge: union laws, collision/legacy/metadata guards, older clocks, retries, server acknowledgement, recovery, queued reload; isolated fake state only');
})().catch(e=>{console.error(e);process.exitCode=1;});